// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhasFinancas.Models;

namespace MinhasFinancas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200303142717_InicialDespresas")]
    partial class InicialDespresas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinhasFinancas.Models.RelatorioDespesa", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("DataDespesa");

                    b.Property<string>("ItemNome")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<decimal>("Valor")
                        .HasColumnType("Decimal(10, 2)");

                    b.HasKey("ItemId");

                    b.ToTable("RelatorioDespesas");
                });
#pragma warning restore 612, 618
        }
    }
}
